services:
  build:
    environment:
      HOSTUID: ${HOSTUID:-1000}
      HOSTGID: ${HOSTGID:-1000}
      VERSION: "${VERSION:-0.1}"
      WORKSPACE: /workspace
      DOCKER_BUILD: 1
    image: andy5995/linuxdeploy:v3-jammy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: "${SCRIPT:-./make-appimage.sh}"
