name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [main, qt-port]
    paths:
    - '**'
    - '!**.md'
    - '**/c-cpp.yml'
  pull_request:
    branches: [main]
    paths:
    - '**'
    - '!**.md'
    - '**/c-cpp.yml'

jobs:
  build:
    name: ${{ matrix.build.name }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: ubuntu-22.04-gcc
            os: ubuntu-22.04
            cc: gcc
          #- name: ubuntu-22.04-clang
          #  os: ubuntu-22.04
          #  cc: clang

    runs-on: ${{ matrix.build.os }}
    env:
      CC: '${{ matrix.build.cc }}'

    steps:
    - uses: actions/checkout@v4

    - name: Set CXX
      if: ${{ env.CC }}
      run: |
        if [ "$CC" = "gcc" ]; then
          echo "CXX=g++" >> $GITHUB_ENV
        else
          echo "CXX=clang++" >> $GITHUB_ENV
        fi

    - name: Show info
      run: |
        export -p
        echo '${{ toJSON(matrix) }}'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get remove -y firefox || true
        sudo apt-get upgrade -y
        sudo apt-get install -y \
          build-essential \
          meson \
          ninja-build \
          qtbase5-dev \
          qtbase5-dev-tools \
          libqt5gui5 \
          pkg-config

    - name: Build
      run: |
        meson setup build
        ninja -C build

    - name: Test
      run: |
        meson test -C build --print-errorlogs
